### ISSUE TITLE
Adding fast charge patches from maverickjb kernel and plans about updating to 6.8

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#6]
As i can see maverickjb have more advance fuel gauge and charge drivers. Any plans about adding his patches to your kernel? Or your charging driver already works well with xiaomi 33w charger or to support it need PD and PPS support patches? Does the RTC works in your kernel? And very important question is there any plans to updating your kernel to linux 6.8?

**Comment by map220v** [comment]
My kernel only has support for standard PD fast charging(Type-C), custom implementations like PD over Type-A aren't supported. I don't really want to use qualcomm's code from downstream kernel, and also I can't test it anymore, because now my Pad 5 can only boot to edl(unless there is firehose for sm8150 xiaomi that doesn't require auth or has exploitable vulnerability).
I can update kernel to 6.8 but there's no guarantee it will work.
