### ISSUE TITLE
Does the xiaomi keyboard works? And how to adapt kernel to boot from usb

### ISSUE THREAD

**Issue by catmengi** [map220v/sm8150-mainline#9]
Is the xiaomi keyboard works? And how to adapt kernel to boot from usb stick(for testing), which drivers i need to compile into kernel?

**Comment by map220v** [comment]
Xiaomi KB works, you should see it in lsusb.
Kernel should be able to boot rootfs or anything else from usb, I have required usb drivers built in kernel instead of modules.
If you want to boot linux rootfs you need to add this `root=PARTLABEL=linux` to boot.img or kernel cmdline, then create partition on usb stick and call it "linux"

**Comment by catmengi** [comment]
Thanks, sometime i will run my favorite distro there,debian)
